provider:
  name: faas
  gateway: http://localhost:8080

functions:
  helloworld:
    lang: python
    handler: ./helloworld
    image: docwareiy/helloworld
  issue-bot:
    lang: python
    handler: ./issue-bot
    image: docwareiy/issue-bot
    environment:
      write_debug: true
      gateway_hostname: "gateway"
      positive_threshold: 0.25
    environment_file:
    - env.yml
